/* Generated By:JavaCC: Do not edit this line. MatchOpQLParserConstants.java */
package org.terrier.matching.matchops;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MatchOpQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HASH = 6;
  /** RegularExpression Id. */
  int WORD = 7;
  /** RegularExpression Id. */
  int PERIOD = 8;
  /** RegularExpression Id. */
  int BASE64WORD = 9;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 10;
  /** RegularExpression Id. */
  int BAND = 11;
  /** RegularExpression Id. */
  int UW = 12;
  /** RegularExpression Id. */
  int OW = 13;
  /** RegularExpression Id. */
  int SYN = 14;
  /** RegularExpression Id. */
  int TAG = 15;
  /** RegularExpression Id. */
  int COMBINE = 16;
  /** RegularExpression Id. */
  int PREFIX = 17;
  /** RegularExpression Id. */
  int FUZZY = 18;
  /** RegularExpression Id. */
  int BASE64 = 19;
  /** RegularExpression Id. */
  int OPEN_PAREN = 20;
  /** RegularExpression Id. */
  int COLON = 21;
  /** RegularExpression Id. */
  int INT = 22;
  /** RegularExpression Id. */
  int WORD_OR_INT_OR_FLOAT = 23;
  /** RegularExpression Id. */
  int COLON_KV = 24;
  /** RegularExpression Id. */
  int EQUALS = 25;
  /** RegularExpression Id. */
  int OPEN_PAREN_KV = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinIndri = 1;
  /** Lexical state. */
  int WithinCombineKV = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\" \"",
    "\"#\"",
    "<WORD>",
    "\".\"",
    "<BASE64WORD>",
    "\")\"",
    "\"band\"",
    "\"uw\"",
    "\"ow\"",
    "\"syn\"",
    "\"tag\"",
    "\"combine\"",
    "\"prefix\"",
    "\"fuzzy\"",
    "\"base64\"",
    "\"(\"",
    "\":\"",
    "<INT>",
    "<WORD_OR_INT_OR_FLOAT>",
    "\":\"",
    "\"=\"",
    "\"(\"",
  };

}
