/* Generated By:JavaCC: Do not edit this line. TerrierQLParserConstants.java */
package org.terrier.querying.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TerrierQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int WINDOWS_EOL = 2;
  /** RegularExpression Id. */
  int UNIX_EOL = 3;
  /** RegularExpression Id. */
  int OLD_MAC_EOL = 4;
  /** RegularExpression Id. */
  int ALPHANUMERIC = 5;
  /** RegularExpression Id. */
  int REQUIRED = 6;
  /** RegularExpression Id. */
  int NOT_REQUIRED = 7;
  /** RegularExpression Id. */
  int HAT = 8;
  /** RegularExpression Id. */
  int PROXIMITY = 9;
  /** RegularExpression Id. */
  int COLON = 10;
  /** RegularExpression Id. */
  int QUOTE = 11;
  /** RegularExpression Id. */
  int OPEN_DISJUNCTIVE = 12;
  /** RegularExpression Id. */
  int CLOSE_DISJUNCTIVE = 13;
  /** RegularExpression Id. */
  int OPEN_PAREN = 14;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 15;
  /** RegularExpression Id. */
  int FLOAT = 16;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinWeight = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ALPHANUMERIC>",
    "\"+\"",
    "\"-\"",
    "\"^\"",
    "\"~\"",
    "\":\"",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "<FLOAT>",
  };

}
