/* Generated By:JavaCC: Do not edit this line. ClassNameParserConstants.java */
package org.terrier.utility;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ClassNameParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 3;
  /** RegularExpression Id. */
  int COMMA = 4;
  /** RegularExpression Id. */
  int PERIOD = 5;
  /** RegularExpression Id. */
  int OPEN_PAREN = 6;
  /** RegularExpression Id. */
  int PARAM_WORD = 7;
  /** RegularExpression Id. */
  int PARAM_COMMA = 8;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 9;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinBrackets = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\" \"",
    "<WORD>",
    "\",\"",
    "\".\"",
    "\"(\"",
    "<PARAM_WORD>",
    "\",\"",
    "\")\"",
  };

}
